/* PL-300 (Power BI Data Analyst) practice questions.

   Every question here is original, written for DataBites and set in its own
   coffee shop. None is taken from the real exam, which is under NDA. The
   domains follow Microsoft's published skills outline; check the current one
   on Microsoft Learn, because it changes.

   A question: { id, domain, topic, type: 'single' | 'multi' | 'order', stem,
   options, answer: [indices into options], why, lesson?: an id in the
   curriculum that practises the same idea, case?: a case study id }.
   - multi says "Choose two." in its stem and has exactly that many answers.
   - order lists its steps in answer, first to last. options may hold a step
     that doesn't belong, as the real exam does; the stem says "in order".
   - A question with a case belongs to that case study: it only appears after
     the scenario, never on its own.
   tests.html checks all of this. */

export const DOMAINS = [
  { id: 'prepare', name: 'Prepare the data', note: 'Power Query: get, clean, shape and load' },
  { id: 'model', name: 'Model the data', note: 'Relationships, DAX and performance' },
  { id: 'visualize', name: 'Visualize and analyze', note: 'Visuals, interactions and AI visuals' },
  { id: 'deploy', name: 'Deploy and maintain', note: 'Workspaces, security and refresh' },
];

export const QUESTIONS = [

/* ── Prepare the data ──────────────────────────────────── */
{
  id: 'pq-01', domain: 'prepare', topic: 'Unpivot', type: 'single',
  stem: "The cafe's Excel file has one row per drink and one column per month: Jan, Feb, Mar, and so on. You need one row per drink per month, with a Month column and a Cups column. Next year's file will have more month columns. Which Power Query step should you use?",
  options: [
    'Select the month columns, then Unpivot Columns',
    'Select the Drink column, then Unpivot Other Columns',
    'Transpose the table',
    'Pivot the Drink column',
  ],
  answer: [1],
  why: '**Unpivot Other Columns** names the column to keep, so month columns added later are unpivoted too. Unpivoting the selected month columns writes their names into the step, and a new month would be left behind as a column. It is the same idea as `melt` in pandas.',
  lesson: 'wr-05',
},
{
  id: 'pq-02', domain: 'prepare', topic: 'Merge queries', type: 'single',
  stem: 'You have an Orders query and a Customers query. Every order needs the customer\'s city added as a column. What do you use?',
  options: [
    'Append Queries',
    'Merge Queries on the customer ID, then expand the City column',
    'Group By on the customer ID',
    'Combine Files',
  ],
  answer: [1],
  why: '**Merge** is a join: it matches rows on a key and brings columns across, like `pd.merge` or SQL `JOIN`. **Append** stacks rows from queries with the same columns, like a SQL `UNION`.',
  lesson: 'wr-01',
},
{
  id: 'pq-03', domain: 'prepare', topic: 'Join kinds', type: 'single',
  stem: 'In Power Query you want the customers who have never placed an order. You merge Customers (first) with Orders (second). Which join kind do you pick?',
  options: ['Left outer', 'Inner', 'Left anti', 'Full outer'],
  answer: [2],
  why: 'A **left anti** join keeps the rows of the first table that have no match in the second: exactly the customers with no orders. Left outer keeps every customer, matched or not; inner keeps only the matched ones.',
  lesson: 'sq-13',
},
{
  id: 'pq-04', domain: 'prepare', topic: 'Folder source', type: 'single',
  stem: 'A CSV of orders lands in one folder every month, always with the same columns. The report should pick up each new month on refresh, with no edits. What do you do?',
  options: [
    'Get Data from the folder, then Combine Files',
    'Import each CSV and append them',
    'Merge the CSV files on the order ID',
    'Paste each month into one Excel sheet first',
  ],
  answer: [0],
  why: 'The **Folder** connector lists every file in the folder at refresh, and **Combine Files** applies the same steps to each. A new file is simply included. Appending files one by one means editing the report every month.',
  lesson: 'wr-03',
},
{
  id: 'pq-05', domain: 'prepare', topic: 'Data profiling', type: 'single',
  stem: 'Column quality shows 0% errors in a 50,000-row table, but a colleague found bad values near the bottom. What is the most likely explanation?',
  options: [
    'Column quality ignores errors in text columns',
    'Column profiling uses the top 1,000 rows by default',
    'Errors only appear after Close & Apply',
    'Profiling only works with DirectQuery',
  ],
  answer: [1],
  why: 'By default, column profiling in Power Query looks at the **top 1,000 rows**. Switch it to the entire data set in the status bar at the bottom of the editor to profile every row.',
},
{
  id: 'pq-06', domain: 'prepare', topic: 'Data types and locale', type: 'single',
  stem: 'A system in the UK exports dates like 05/02/2024, meaning 5 February. After Changed Type they show as 2 May. How do you fix it?',
  options: [
    'Change Type > Using Locale, with Date and English (United Kingdom)',
    'Change the column to Text',
    'Split the column by / and rebuild the date',
    'Use Replace Values to swap day and month',
  ],
  answer: [0],
  why: '**Using Locale** tells Power Query how the source writes dates, so day and month are read in the right order. Splitting and rebuilding works, but it is more steps to maintain, and it breaks if the format changes.',
  lesson: 'ms-05',
},
{
  id: 'pq-07', domain: 'prepare', topic: 'Fill down', type: 'single',
  stem: 'An Excel export writes each region name only on the first row of its block. The rows under it are empty (null). Which step puts the region on every row?',
  options: ['Fill Down', 'Fill Up', 'Remove Blank Rows', 'Replace Errors'],
  answer: [0],
  why: '**Fill Down** copies each value into the nulls below it, until the next value. Fill Up goes the other way. Removing blank rows would throw the data away.',
},
{
  id: 'pq-08', domain: 'prepare', topic: 'Query folding', type: 'single',
  stem: 'You connect to SQL Server and add a filter step. How can you check whether that step is folded back to the database?',
  options: [
    'Right-click the step: View Native Query is available',
    'Column quality shows 100% valid',
    'Enable Load is ticked for the query',
    'The step appears after Changed Type',
  ],
  answer: [0],
  why: 'When a step folds, Power Query turns it into the source\'s own query language, and **View Native Query** shows that query. When it is greyed out, the step (or one before it) did not fold.',
},
{
  id: 'pq-09', domain: 'prepare', topic: 'Query folding', type: 'single',
  stem: 'A query against a database loads ten years of orders, but the report only needs the last two. Where should the filter go?',
  options: [
    'As early as possible in the Power Query steps',
    'As the last Power Query step',
    'In a visual-level filter',
    'In a DAX measure',
  ],
  answer: [0],
  why: 'An early filter can **fold** into the database query, so only two years travel over the network and into the model. Once a step that can\'t fold has run, the steps after it can\'t fold either. A visual or DAX filter still loads all ten years.',
},
{
  id: 'pq-10', domain: 'prepare', topic: 'Enable load', type: 'single',
  stem: 'A staging query, Raw Orders, only feeds other queries. It should not become a table in the model. What do you do?',
  options: [
    'Delete it',
    'Right-click it and untick Enable Load',
    'Hide the table in Model view',
    'Change every column to Text',
  ],
  answer: [1],
  why: 'With **Enable Load** off, the query still runs and feeds the queries that use it, but it isn\'t loaded as a table. Hiding a table in Model view still loads it and uses memory. Deleting it breaks the queries that depend on it.',
},
{
  id: 'pq-11', domain: 'prepare', topic: 'Reference and duplicate', type: 'single',
  stem: 'You want a second query that starts from the finished output of Orders, and picks up any change you later make to the Orders steps. Which do you use?',
  options: ['Duplicate', 'Reference', 'Append', 'Merge'],
  answer: [1],
  why: '**Reference** makes a new query whose source is the other query\'s output, so later changes flow through. **Duplicate** copies the steps once; after that the two queries are independent.',
},
{
  id: 'pq-12', domain: 'prepare', topic: 'Data types', type: 'single',
  stem: 'The price column holds money, and totals must add up to the penny without floating-point surprises. Which data type do you pick?',
  options: ['Decimal Number', 'Fixed Decimal Number', 'Whole Number', 'Text'],
  answer: [1],
  why: '**Fixed Decimal Number** (the currency type) stores exactly four digits after the decimal point, so sums don\'t pick up tiny rounding errors. Decimal Number is a floating-point number.',
},
{
  id: 'pq-13', domain: 'prepare', topic: 'Storage modes', type: 'multi',
  stem: 'A sales database has 200 million rows, and users need to see changes within minutes rather than after a scheduled refresh. You consider DirectQuery. Which two statements about DirectQuery are true? Choose two.',
  options: [
    'Data stays in the source and is queried when visuals load',
    'Visuals are usually faster than with Import',
    'Some Power Query transformations and DAX functions are limited',
    'The data is copied into the model up to 48 times a day',
  ],
  answer: [0, 2],
  why: 'With **DirectQuery**, visuals send queries to the source each time, so they show current data, but they depend on the source\'s speed and are usually slower than **Import**. Some Power Query steps and DAX functions are restricted, because everything has to translate into source queries.',
},
{
  id: 'pq-14', domain: 'prepare', topic: 'Parameters', type: 'single',
  stem: 'The same report connects to a test server while you build it and a production server when it goes live. How do you switch between them without editing every query?',
  options: [
    'Create a parameter for the server name and use it in each source step',
    'Duplicate every query for each server',
    'Use a DAX variable for the server name',
    'Change the data gateway',
  ],
  answer: [0],
  why: 'A Power Query **parameter** holds the server name in one place. Change it once, in Desktop or in the semantic model\'s settings in the service, and every query that uses it follows.',
},
{
  id: 'pq-15', domain: 'prepare', topic: 'Errors', type: 'single',
  stem: 'A Spend column mixes 12.50, £18.00 and n/a. Changing it to a number gives errors on some rows. You want to see exactly which rows fail before deciding what to do. Which step?',
  options: ['Keep Errors', 'Remove Errors', 'Replace Errors with 0', 'Change the type to Text'],
  answer: [0],
  why: '**Keep Errors** shows only the failing rows, so you can see the problem, here the £ sign and the n/a. Remove Errors and Replace Errors are decisions to make after you know what the errors are.',
  lesson: 'ms-04',
},
{
  id: 'pq-16', domain: 'prepare', topic: 'Reducing rows', type: 'single',
  stem: 'Orders are stored one row per order line, but every report only shows daily totals per product. How do you make the model smaller?',
  options: [
    'Group By date and product in Power Query, summing the quantity',
    'Hide the order line columns',
    'Add a calculated table of daily totals',
    'Create a date hierarchy',
  ],
  answer: [0],
  why: 'Grouping in Power Query loads fewer rows, so the model is smaller and faster. Hiding columns or adding a calculated table still loads every line.',
  lesson: 'pd-09',
},
{
  id: 'pq-17', domain: 'prepare', topic: 'Dataflows', type: 'single',
  stem: 'Several reports across the team use the same cleaned customer table. You want the cleaning done once and reused, not copied into every report. What do you create?',
  options: [
    'A dataflow in the Power BI service',
    'A copy of the queries in every PBIX file',
    'A Publish to web link',
    'A report page tooltip',
  ],
  answer: [0],
  why: 'A **dataflow** runs Power Query in the service and stores the result, and any report can use it as a source. Fix the cleaning once, and every report picks it up.',
},
{
  id: 'pq-18', domain: 'prepare', topic: 'Headers', type: 'single',
  stem: 'A CSV loads with generic column names (Column1, Column2 ...), and the real names sit in the first row of data. Which step fixes it?',
  options: ['Use First Row as Headers', 'Transpose', 'Rename each column by hand', 'Remove Top Rows'],
  answer: [0],
  why: '**Use First Row as Headers** (Promote Headers) turns the first row into column names in one step. Removing the top row would throw the names away.',
},

/* ── Model the data ────────────────────────────────────── */
{
  id: 'md-01', domain: 'model', topic: 'Star schema', type: 'single',
  stem: 'In the shop model (`customers`, `products`, `calendar`, `orders` and `order_items`), which is a fact table?',
  options: ['`products`', '`customers`', '`order_items`', '`calendar`'],
  answer: [2],
  why: 'A **fact table** records events at a set grain (here, one line of an order) with keys to the dimensions and numbers to add up. **Dimension** tables such as products and customers describe those events, and are what you slice by.',
  lesson: 'dx-05',
},
{
  id: 'md-02', domain: 'model', topic: 'Relationships', type: 'single',
  stem: 'The `products` table has one row per product; `order_items` has many lines per product. What relationship suits a standard star schema?',
  options: [
    'One-to-many, filtering in a single direction from products to order_items',
    'Many-to-many, filtering in both directions',
    'One-to-one, filtering in both directions',
    'One-to-many, filtering from order_items to products',
  ],
  answer: [0],
  why: 'One product, many lines: **one-to-many**. In a star schema the dimension filters the fact, **single direction**, so slicing by category reaches the order lines, and nothing filters back up.',
  lesson: 'dx-05',
},
{
  id: 'md-03', domain: 'model', topic: 'Role-playing dimension', type: 'single',
  stem: 'The `orders` table has an order date and a ship date, both related to one `calendar` table. Only one of those relationships can be active. How do you calculate sales by ship date?',
  options: [
    'Make both relationships active',
    'Keep the ship date relationship inactive, and use USERELATIONSHIP inside CALCULATE',
    'Use RELATEDTABLE on the ship date',
    'Set the ship date relationship to filter in both directions',
  ],
  answer: [1],
  why: '`CALCULATE([Sales], USERELATIONSHIP(orders[ship_date], calendar[date]))` switches that one measure onto the inactive relationship. The calendar plays two roles. A copy of the date table, one per role, is the other common fix.',
},
{
  id: 'md-04', domain: 'model', topic: 'Date table', type: 'multi',
  stem: 'You want to mark calendar as the date table. Which two are required of its date column? Choose two.',
  options: [
    'Unique values, with no blanks',
    'Every date in the range, with no gaps',
    'A Month Name column alongside it',
    'The table must start on 1 January',
  ],
  answer: [0, 1],
  why: 'To be marked as a date table, the date column must hold **unique, non-blank** dates covering a **continuous range**. Whole years are good practice for time intelligence, but aren\'t required; a Month Name column is nice to have.',
  lesson: 'dx-14',
},
{
  id: 'md-05', domain: 'model', topic: 'Sort by column', type: 'single',
  stem: 'A chart shows months in alphabetical order: April, August, December ... How do you fix it?',
  options: [
    'Sort the Month Name column by a Month Number column',
    'Rename the months to start with their number',
    'Put the months in a hierarchy',
    'Change Month Name to a Date type',
  ],
  answer: [0],
  why: '**Sort by Column** (in the Column tools ribbon) sorts one column by another. Sort Month Name by Month Number and every visual uses calendar order.',
},
{
  id: 'md-06', domain: 'model', topic: 'Measures and columns', type: 'single',
  stem: 'Profit margin must come out right for whatever slicers and filters a user picks: any product, month or city. What do you create?',
  options: ['A measure', 'A calculated column', 'A calculated table', 'A Power Query custom column'],
  answer: [0],
  why: 'A **measure** is worked out at query time, in the filter context of each cell, so it responds to every filter. A calculated column is worked out once per row at refresh, and a margin can\'t simply be added up across rows.',
  lesson: 'pbi-01',
},
{
  id: 'md-07', domain: 'model', topic: 'Measures and columns', type: 'single',
  stem: 'You need a Price Band (premium or standard) that users can pick in a slicer. What do you create?',
  options: ['A calculated column', 'A measure', 'A quick measure', 'A report page tooltip'],
  answer: [0],
  why: 'Slicers, rows and axes need a **column**: a value stored on each row. A measure can\'t be placed in a slicer. A Power Query column would work just as well.',
  lesson: 'pbi-01',
},
{
  id: 'md-08', domain: 'model', topic: 'DAX: CALCULATE', type: 'single',
  stem: "In a matrix by category, you want each category's share of all sales. Which measure is right on every row?",
  options: [
    'DIVIDE([Sales], CALCULATE([Sales], ALL(products)))',
    'DIVIDE([Sales], SUM(order_items[qty]))',
    '[Sales] / COUNTROWS(products)',
    'CALCULATE([Sales], products[category])',
  ],
  answer: [0],
  why: '`CALCULATE([Sales], ALL(products))` removes the category filter, so the bottom of the fraction is every sale, on every row. The row\'s own [Sales] on top gives its share.',
  lesson: 'dx-08',
},
{
  id: 'md-09', domain: 'model', topic: 'DAX: DIVIDE', type: 'single',
  stem: 'Why use DIVIDE([A], [B]) instead of [A] / [B]?',
  options: [
    'DIVIDE gives BLANK, or a value you choose, instead of an error when B is zero',
    'Measures must use DIVIDE',
    'The / operator rounds to whole numbers',
    'DIVIDE ignores the filters on B',
  ],
  answer: [0],
  why: '**DIVIDE** handles a zero or blank denominator: it returns BLANK by default, or its third argument. That keeps a divide-by-zero from breaking a visual.',
  lesson: 'dx-03',
},
{
  id: 'md-10', domain: 'model', topic: 'Time intelligence', type: 'single',
  stem: 'Beside each month\'s sales, you want the same month last year. Which measure?',
  options: [
    'CALCULATE([Sales], SAMEPERIODLASTYEAR(calendar[date]))',
    'TOTALYTD([Sales], calendar[date])',
    'CALCULATE([Sales], DATESYTD(calendar[date]))',
    '[Sales] - 365',
  ],
  answer: [0],
  why: '**SAMEPERIODLASTYEAR** shifts the dates showing back one year, and CALCULATE works out [Sales] for them. TOTALYTD and DATESYTD give a running total from 1 January.',
  lesson: 'dx-15',
},
{
  id: 'md-11', domain: 'model', topic: 'Time intelligence', type: 'single',
  stem: 'Time intelligence functions such as TOTALYTD and DATEADD depend on what?',
  options: [
    'A date table with a continuous range of dates, related to the fact table',
    'A Date column formatted as text',
    'Auto date/time being switched off',
    'A hierarchy of year, quarter and month',
  ],
  answer: [0],
  why: 'They work by shifting and extending the **dates in a date table**, so they need one with every date, related to your facts. Marking it as the date table tells Power BI which one to use.',
  lesson: 'dx-14',
},
{
  id: 'md-12', domain: 'model', topic: 'Filter direction', type: 'single',
  stem: 'What is the main risk of setting a relationship to filter in both directions?',
  options: [
    'Ambiguous filter paths and slower queries',
    'Row-level security stops working',
    'The relationship becomes many-to-many',
    'RELATED stops working',
  ],
  answer: [0],
  why: 'Filters flowing both ways can reach a table by more than one path, which is **ambiguous**, and they make queries do more work. When one measure needs it, **CROSSFILTER** inside CALCULATE switches it on for that measure alone.',
  lesson: 'pbi-04',
},
{
  id: 'md-13', domain: 'model', topic: 'Many-to-many', type: 'single',
  stem: 'A customer can belong to several segments, and a segment has many customers. What is the recommended way to model this?',
  options: [
    'A bridge table with one row per customer-segment pair, related one-to-many to both',
    'A text column listing each customer\'s segments, separated by commas',
    'Merge segments into customers in Power Query',
    'A one-to-one relationship filtering in both directions',
  ],
  answer: [0],
  why: 'A **bridge table** turns many-to-many into two one-to-many relationships, which filter predictably. A comma-separated column can\'t be filtered or joined properly.',
},
{
  id: 'md-14', domain: 'model', topic: 'Performance', type: 'single',
  stem: 'What happens when you switch off Auto date/time in Power BI Desktop\'s options?',
  options: [
    'The hidden date table Power BI builds for every date column goes, making the model smaller',
    'Time intelligence stops working in every model',
    'Date slicers stop working',
    'Scheduled refresh is disabled',
  ],
  answer: [0],
  why: '**Auto date/time** creates a hidden date table for each date column. Switch it off and use one proper date table instead. The model gets smaller, and every date works the same way.',
},
{
  id: 'md-15', domain: 'model', topic: 'Performance', type: 'multi',
  stem: 'The model is too big and slow. Which two changes help? Choose two.',
  options: [
    'Remove columns no report uses',
    'Reduce high-cardinality columns, for example split a date-time into separate date and time columns',
    'Set every relationship to filter in both directions',
    'Add a calculated column for every measure',
  ],
  answer: [0, 1],
  why: 'The model compresses best with **fewer columns** and **fewer distinct values** in each. A date-time has a huge number of distinct values; a date and a time separately have far fewer.',
},
{
  id: 'md-16', domain: 'model', topic: 'Performance', type: 'single',
  stem: 'A report page is slow to load. Which tool shows how long each visual\'s query takes?',
  options: ['Performance Analyzer', 'Column quality', 'Lineage view', 'The Sync slicers pane'],
  answer: [0],
  why: '**Performance Analyzer** (on the Optimize ribbon in recent versions) records each visual\'s DAX query and rendering time, and lets you copy the query to look at it further.',
},
{
  id: 'md-17', domain: 'model', topic: 'Context transition', type: 'single',
  stem: 'Inside SUMX over customers, [Sales] gives each customer\'s own sales, but writing out the Sales formula in full gives everyone\'s total on every row. Why?',
  options: [
    'A measure reference runs inside an implicit CALCULATE, which turns the current row into a filter',
    'SUMX ignores filters',
    'Measures are worked out at refresh',
    'The formula needs RELATED',
  ],
  answer: [0],
  why: 'That is **context transition**. A measure used inside an iterator gets the row it is on as a filter; the same formula written out does not, unless you wrap it in CALCULATE.',
  lesson: 'dx-21',
},
{
  id: 'md-18', domain: 'model', topic: 'DAX: RANKX', type: 'single',
  stem: 'You want each product ranked by sales, 1 for the best, and correct in a matrix that shows one product per row. Which measure?',
  options: [
    'RANKX(ALL(products[name]), [Sales])',
    'RANKX(products, [Sales])',
    'TOPN(1, products, [Sales])',
    'MAXX(products, [Sales])',
  ],
  answer: [0],
  why: 'On a product\'s row, `products` holds just that product, so ranking against it always gives 1. `ALL(products[name])` ranks against every product.',
  lesson: 'dx-13',
},
{
  id: 'md-19', domain: 'model', topic: 'Summarization', type: 'single',
  stem: 'Visuals add up the Year column (2024 + 2024 + ...) instead of listing years. What is the best fix?',
  options: [
    "Set the column's default summarization to Don't summarize",
    'Delete the column',
    'Hide the column',
    'Mark the table as a date table',
  ],
  answer: [0],
  why: "A number column is summed by default. **Don't summarize** makes visuals treat it as a category.",
},
{
  id: 'md-20', domain: 'model', topic: 'Keys', type: 'single',
  stem: 'Why is a whole-number key usually better than a long text key for relationships?',
  options: [
    'Whole numbers compress better, so the model is smaller and faster',
    'Text keys can\'t be used in relationships',
    'Whole numbers sort alphabetically',
    'Text keys stop DAX working',
  ],
  answer: [0],
  why: 'Relationships work on the key\'s values. **Whole numbers** take less memory than long text and compress better, so the model is smaller and queries are faster.',
},

/* ── Visualize and analyze ─────────────────────────────── */
{
  id: 'vz-01', domain: 'visualize', topic: 'Choosing a visual', type: 'single',
  stem: 'You want to show how monthly sales changed over the year. Which visual?',
  options: ['Line chart', 'Pie chart', 'Scatter chart', 'Card'],
  answer: [0],
  why: 'A **line chart** shows change over time at a glance. A pie chart compares parts of one whole; a scatter shows two measures against each other.',
},
{
  id: 'vz-02', domain: 'visualize', topic: 'Choosing a visual', type: 'single',
  stem: 'You want to compare sales across 12 products so the best seller stands out. Which visual?',
  options: ['A bar chart sorted from highest to lowest', 'A pie chart', 'A line chart', 'A gauge'],
  answer: [0],
  why: '**Bars sorted by value** make ranking easy to read. Twelve pie slices are hard to compare, and a line suggests a sequence the products don\'t have.',
  lesson: 'mp-04',
},
{
  id: 'vz-03', domain: 'visualize', topic: 'Slicers', type: 'single',
  stem: 'A Region slicer on page 1 should filter pages 2 and 3 as well. What do you use?',
  options: ['The Sync slicers pane', 'Edit interactions', 'Bookmarks', 'Drillthrough'],
  answer: [0],
  why: 'The **Sync slicers** pane (on the View ribbon) keeps a slicer\'s selection the same across the pages you choose, and can add the slicer to them.',
},
{
  id: 'vz-04', domain: 'visualize', topic: 'Interactions', type: 'single',
  stem: 'Clicking a bar in one chart should not change a card on the same page. What do you do?',
  options: [
    'Edit interactions, and set the card to None for that chart',
    'Delete the relationship between the tables',
    'Hide the card when the chart is clicked',
    'Lock the card\'s position',
  ],
  answer: [0],
  why: '**Edit interactions** (Format ribbon) sets how each visual responds to a selection in another: filter, highlight or **none**.',
},
{
  id: 'vz-05', domain: 'visualize', topic: 'Drillthrough', type: 'single',
  stem: 'From any page, users should be able to right-click a product and open a detail page showing only that product. What do you build?',
  options: [
    'A drillthrough page, with Product as the drillthrough field',
    'A bookmark for each product',
    'A report page tooltip',
    'A drill-down hierarchy',
  ],
  answer: [0],
  why: 'A **drillthrough** page has a drillthrough field. Right-click a data point for that field anywhere in the report, and the page opens filtered to it.',
},
{
  id: 'vz-06', domain: 'visualize', topic: 'Tooltips', type: 'single',
  stem: 'Hovering over a product\'s bar should show a small chart of that product\'s monthly sales. What do you build?',
  options: ['A report page tooltip', 'A drillthrough page', 'A bookmark', 'Conditional formatting'],
  answer: [0],
  why: 'A **report page tooltip** is a small page, set to be used as a tooltip, that shows up on hover, filtered to the data point under the pointer.',
},
{
  id: 'vz-07', domain: 'visualize', topic: 'Bookmarks', type: 'single',
  stem: 'Two buttons should switch the same page between a chart and a table. What do you use?',
  options: [
    'Bookmarks that show and hide visuals through the Selection pane, run by the buttons',
    'A drillthrough page',
    'Sync slicers',
    'A page navigator',
  ],
  answer: [0],
  why: 'A **bookmark** remembers which visuals are shown and hidden. Two bookmarks, one per view, with a **button** for each, gives the switch.',
},
{
  id: 'vz-08', domain: 'visualize', topic: 'Field parameters', type: 'single',
  stem: 'With one slicer, users should switch a chart between Sales, Units and Orders, without a bookmark for each. What do you use?',
  options: ['A field parameter', 'Sync slicers', 'A drillthrough page', 'A report page tooltip'],
  answer: [0],
  why: 'A **field parameter** lists the measures, or columns, to choose between, and puts a slicer on the page that swaps them in the visual.',
},
{
  id: 'vz-09', domain: 'visualize', topic: 'Conditional formatting', type: 'single',
  stem: 'Margin cells in a table should turn red below 10% and green above 25%. What do you use?',
  options: [
    'Conditional formatting: background colour by rules',
    'A report theme',
    'A bookmark',
    'The Data colours setting for the whole column',
  ],
  answer: [0],
  why: '**Conditional formatting** by rules colours each cell by its own value. A theme or one colour setting colours everything the same.',
},
{
  id: 'vz-10', domain: 'visualize', topic: 'Themes', type: 'single',
  stem: "Every report should use the company's colours and fonts, the same way. What is the most efficient approach?",
  options: [
    'Create a report theme (a JSON file) and apply it to each report',
    'Format every visual by hand',
    'Use conditional formatting',
    'Publish an app',
  ],
  answer: [0],
  why: 'A **theme** sets colours, fonts and visual defaults in one file, and any report can apply it.',
},
{
  id: 'vz-11', domain: 'visualize', topic: 'Top N', type: 'single',
  stem: 'A visual should show the 5 best-selling products, and update as the data and slicers change. What do you use?',
  options: [
    'A Top N filter on product, by Sales, in the Filters pane',
    'Sort the visual and hide the other rows by hand',
    'A calculated table built with TOPN',
    'A bookmark',
  ],
  answer: [0],
  why: 'A **Top N** filter is re-evaluated with every slicer selection. A calculated table is worked out once, at refresh, so it wouldn\'t respond to slicers.',
  lesson: 'dx-23',
},
{
  id: 'vz-12', domain: 'visualize', topic: 'AI visuals', type: 'single',
  stem: 'You want to find which factors most affect whether a customer\'s rating is low. Which visual?',
  options: ['Key influencers', 'Decomposition tree', 'Scatter chart', 'Funnel chart'],
  answer: [0],
  why: '**Key influencers** analyses which fields most change the value of what you choose to analyse, and ranks them. The decomposition tree breaks a total down; it doesn\'t rank drivers.',
},
{
  id: 'vz-13', domain: 'visualize', topic: 'AI visuals', type: 'single',
  stem: 'A manager wants to break total sales down by region, then product, then month, picking the order as they go. Which visual?',
  options: ['Decomposition tree', 'Key influencers', 'Matrix with a fixed hierarchy', 'Ribbon chart'],
  answer: [0],
  why: 'The **decomposition tree** lets the viewer choose the next field to split by at each level, and can suggest the split with the highest or lowest value.',
},
{
  id: 'vz-14', domain: 'visualize', topic: 'Analytics pane', type: 'single',
  stem: 'A line chart of monthly sales should show a projection for the next three months. What do you add?',
  options: [
    'A forecast, from the Analytics pane',
    'A trend line',
    'A constant line',
    'Error bars',
  ],
  answer: [0],
  why: 'The **forecast** option in the Analytics pane projects a line chart forward, with a confidence band. It needs a continuous date axis. A trend line only fits the existing points.',
},
{
  id: 'vz-15', domain: 'visualize', topic: 'Accessibility', type: 'single',
  stem: 'Which change makes a report easier for screen reader users?',
  options: [
    'Add alt text to visuals and set a sensible tab order',
    'Show status by colour alone',
    'Remove visual titles to reduce clutter',
    'Use more pie charts',
  ],
  answer: [0],
  why: '**Alt text** is what a screen reader reads out for a visual, and **tab order** sets the order visuals are reached by keyboard. Colour alone leaves out anyone who can\'t see it.',
},
{
  id: 'vz-16', domain: 'visualize', topic: 'Paginated reports', type: 'single',
  stem: 'Finance needs a printable, invoice-style report that runs to many pages with an exact layout. What do you build?',
  options: [
    'A paginated report, in Power BI Report Builder',
    'A dashboard',
    'A mobile layout',
    'A report page tooltip',
  ],
  answer: [0],
  why: '**Paginated reports** are for pixel-exact, multi-page documents for printing or PDF. Power BI reports are built for interactive exploration on screen.',
},
{
  id: 'vz-17', domain: 'visualize', topic: 'Mobile', type: 'single',
  stem: 'A report page should be easy to use on a phone. What do you do?',
  options: [
    'Arrange the visuals in the Mobile layout view',
    'Make a copy of the page with a smaller canvas',
    'Apply a theme',
    'Use Publish to web',
  ],
  answer: [0],
  why: 'The **Mobile layout** view lets you place the page\'s visuals for a portrait phone screen. The phone app then shows that layout.',
},
{
  id: 'vz-18', domain: 'visualize', topic: 'Grouping', type: 'single',
  stem: 'Customer ages should appear on an axis in ranges of 10 years. What do you use?',
  options: ['Bins (New group, of type Bin)', 'A hierarchy', 'Drill down', 'A measure'],
  answer: [0],
  why: '**Binning** groups a number or date column into equal-sized ranges you choose. It is the same idea as `pd.cut`.',
  lesson: 'pd-19',
},

/* ── Deploy and maintain ───────────────────────────────── */
{
  id: 'dp-01', domain: 'deploy', topic: 'Workspace roles', type: 'single',
  stem: 'A colleague should create and publish content in your workspace, but must not add or remove people. Which role?',
  options: ['Contributor', 'Viewer', 'Member', 'Admin'],
  answer: [0],
  why: '**Contributor** can create, edit and publish content. **Member** can also add people and share, and **Admin** can manage everything. **Viewer** can only view.',
},
{
  id: 'dp-02', domain: 'deploy', topic: 'Apps', type: 'single',
  stem: 'You need to share finished reports with 200 people in sales, without giving them access to the workspace. What do you do?',
  options: [
    'Publish an app from the workspace',
    'Add everyone as a workspace Member',
    'Use Publish to web',
    'Export the reports to PDF',
  ],
  answer: [0],
  why: 'An **app** packages a workspace\'s content for a wide audience, read-only, and updates when you republish. The people who build it keep their workspace to themselves.',
},
{
  id: 'dp-03', domain: 'deploy', topic: 'Row-level security', type: 'single',
  stem: "Each regional manager should see only their own region's rows, in the same report. What do you set up?",
  options: [
    'Row-level security: a role with a DAX filter, and its members assigned in the service',
    'A separate report for each region',
    'A page-level filter',
    'Hide the Region column',
  ],
  answer: [0],
  why: '**RLS** roles filter the data itself for each user. Filters in a report can be changed or cleared by the viewer; RLS can\'t.',
},
{
  id: 'dp-04', domain: 'deploy', topic: 'Dynamic RLS', type: 'single',
  stem: 'One RLS role should serve every manager, each seeing only their own rows. The table has a Manager Email column. Which DAX filter?',
  options: [
    '[Manager Email] = USERPRINCIPALNAME()',
    '[Manager Email] = SELECTEDVALUE([Manager Email])',
    'ALL([Manager Email])',
    'A slicer on Manager Email',
  ],
  answer: [0],
  why: '**USERPRINCIPALNAME()** returns the signed-in user\'s sign-in name, usually their email address, so one role filters each person to their own rows. That is **dynamic RLS**.',
},
{
  id: 'dp-05', domain: 'deploy', topic: 'Row-level security', type: 'single',
  stem: 'A colleague with the Member role in the workspace says RLS doesn\'t restrict what they see. Why?',
  options: [
    'RLS applies to Viewers; Admins, Members and Contributors can edit the content, so they see all the data',
    'RLS only works in Power BI Desktop',
    'RLS needs a gateway',
    'Members are always removed from RLS roles',
  ],
  answer: [0],
  why: 'RLS only restricts people with **view-only** access (the Viewer role, or an app or share). Anyone who can edit the semantic model sees everything.',
},
{
  id: 'dp-06', domain: 'deploy', topic: 'Testing RLS', type: 'single',
  stem: 'How do you test an RLS role in Power BI Desktop before publishing?',
  options: [
    'Modeling > View as, and choose the role',
    'Publish, then ask a user to check',
    'Run Performance Analyzer',
    'Open Lineage view',
  ],
  answer: [0],
  why: '**View as** shows the report as a member of the roles you pick. In the service, the semantic model\'s security settings have a Test as role option too.',
},
{
  id: 'dp-07', domain: 'deploy', topic: 'Gateways', type: 'single',
  stem: 'The data is in a SQL Server in your office, and the report needs scheduled refresh in the service. What else do you need?',
  options: [
    'An on-premises data gateway',
    'Nothing: the service connects to it directly',
    'A Publish to web link',
    'A dataflow',
  ],
  answer: [0],
  why: 'The service can\'t reach inside your network by itself. An **on-premises data gateway**, installed on a machine that can reach the server, relays the refresh.',
},
{
  id: 'dp-08', domain: 'deploy', topic: 'Gateways', type: 'single',
  stem: 'The data is in Azure SQL Database, reachable from the internet. Do you need a gateway for scheduled refresh?',
  options: [
    'No: the service connects to a cloud source directly',
    'Yes: every scheduled refresh needs one',
    'Only for DirectQuery',
    'Only for more than 8 refreshes a day',
  ],
  answer: [0],
  why: 'A **cloud source** the service can reach needs no gateway. Gateways are for data it can\'t reach itself, such as on-premises servers or private networks.',
},
{
  id: 'dp-09', domain: 'deploy', topic: 'Refresh', type: 'single',
  stem: 'A semantic model is in a workspace on shared capacity, with Pro licences. How many scheduled refreshes a day can it have?',
  options: ['Up to 8', 'Up to 48', 'Unlimited', 'One'],
  answer: [0],
  why: 'Shared capacity (Pro) allows **8** scheduled refreshes a day. A Premium or Fabric capacity allows up to 48.',
},
{
  id: 'dp-10', domain: 'deploy', topic: 'Incremental refresh', type: 'single',
  stem: 'To set up incremental refresh, which parameters must you create in Power Query?',
  options: [
    'RangeStart and RangeEnd, of type Date/Time',
    'StartDate and EndDate, of type Text',
    'Year and Month, of type Whole Number',
    'A single Refresh parameter, of type True/False',
  ],
  answer: [0],
  why: 'Incremental refresh uses two **Date/Time** parameters named exactly **RangeStart** and **RangeEnd**, used to filter the table. The service fills them in to refresh only the recent partitions.',
},
{
  id: 'dp-11', domain: 'deploy', topic: 'Endorsement', type: 'single',
  stem: 'You want a semantic model marked as a trusted, company-wide source, a label only approved reviewers can apply. Which endorsement?',
  options: ['Certified', 'Promoted', 'Featured', 'Pinned'],
  answer: [0],
  why: 'Anyone with write access can **promote** content. **Certified** is for the people an admin has allowed to certify, and signals an official source.',
},
{
  id: 'dp-12', domain: 'deploy', topic: 'Subscriptions', type: 'single',
  stem: 'A manager wants a snapshot of a report page by email every Monday morning. What do you set up?',
  options: ['A subscription', 'A data alert', 'A bookmark', 'A dashboard tile'],
  answer: [0],
  why: 'A **subscription** emails a snapshot of a report page or dashboard on a schedule.',
},
{
  id: 'dp-13', domain: 'deploy', topic: 'Alerts', type: 'single',
  stem: "You want a notification when a KPI's value drops below 100. What do you set up?",
  options: [
    'A data alert on a dashboard tile',
    'A subscription',
    'Row-level security',
    'A sensitivity label',
  ],
  answer: [0],
  why: '**Data alerts** are set on dashboard tiles showing a single number: cards, KPIs and gauges. Pin the visual to a dashboard, then add the alert to its tile.',
},
{
  id: 'dp-14', domain: 'deploy', topic: 'Sharing', type: 'single',
  stem: 'Why should you not use Publish to web for internal financial reports?',
  options: [
    'It makes the report public: anyone with the link or embed code can see it, without signing in',
    'It only works on mobile',
    'It removes the report from the workspace',
    'It needs Premium capacity',
  ],
  answer: [0],
  why: '**Publish to web** is for public data. For anything internal, share it, publish an app, or use secure embedding, all of which need a sign-in.',
},
{
  id: 'dp-15', domain: 'deploy', topic: 'Licensing', type: 'single',
  stem: 'Your workspace is on shared capacity, not Premium or Fabric. What do colleagues need to view the reports you share with them?',
  options: [
    'A Pro or Premium Per User licence of their own',
    'Nothing: a free licence is enough',
    'Power BI Desktop installed',
    'A workspace Admin role',
  ],
  answer: [0],
  why: 'On shared capacity, both the person sharing and the viewer need **Pro** (or Premium Per User). Content in a Premium or Fabric capacity (F64 or larger) can be viewed with a free licence.',
},
{
  id: 'dp-16', domain: 'deploy', topic: 'Sensitivity labels', type: 'single',
  stem: 'A report should be classified Confidential, and the classification should go with data exported to Excel. What do you apply?',
  options: [
    'A Microsoft Purview sensitivity label',
    'Row-level security',
    'Certified endorsement',
    'The Viewer workspace role',
  ],
  answer: [0],
  why: '**Sensitivity labels** classify content, and the label follows supported exports such as Excel, PowerPoint and PDF files.',
},
{
  id: 'dp-17', domain: 'deploy', topic: 'Deployment pipelines', type: 'single',
  stem: 'Content should move from a development workspace to test and then production, with a comparison of what changed at each stage. What do you use?',
  options: ['Deployment pipelines', 'Apps', 'Dataflows', 'Template apps'],
  answer: [0],
  why: '**Deployment pipelines** link development, test and production workspaces, compare them, and deploy content from one stage to the next. They need Premium, Premium Per User or Fabric capacity.',
},
{
  id: 'dp-18', domain: 'deploy', topic: 'Reuse', type: 'single',
  stem: 'A colleague wants to build a new report on your published semantic model, without making a copy of it. What do they need?',
  options: [
    'Build permission, then connect to the semantic model from Power BI Desktop',
    'A copy of your PBIX file',
    'The workspace Admin role',
    'A Publish to web link',
  ],
  answer: [0],
  why: 'With **Build** permission, they can connect live to the published semantic model and make their own report, while the model and its security stay in one place.',
},

/* ── Put the steps in order ────────────────────────────── */
{
  id: 'pq-19', domain: 'prepare', topic: 'Merge queries', type: 'order',
  stem: 'Every order in the Orders query needs the customer\'s city. Four of these actions do it. Put them in order.',
  options: [
    'Select the Orders query',
    'Merge Queries, choose Customers, and match the customer_id columns',
    'Choose Left Outer as the join kind',
    'Expand the new Customers column, keeping only City',
    'Append Queries, choosing Customers',
  ],
  answer: [0, 1, 2, 3],
  why: 'A merge starts from the query that keeps all its rows (Orders), matches on the key, and **Left Outer** keeps every order even without a customer. The merged table arrives as one nested column; **expanding** it brings City across. Append would stack the two tables instead.',
  lesson: 'wr-01',
},
{
  id: 'pq-20', domain: 'prepare', topic: 'Unpivot', type: 'order',
  stem: 'The targets file has the column names in its first row, then one row per drink and one column per month. Put the steps that give one row per drink per month in order.',
  options: [
    'Use First Row as Headers',
    'Select the Drink column',
    'Unpivot Other Columns',
    'Rename the Attribute column to Month',
    'Transpose the table',
  ],
  answer: [0, 1, 2, 3],
  why: 'Headers come first, so the columns have their real names. Then select the column to **keep** and unpivot the rest. Unpivoting creates Attribute and Value columns, so renaming Attribute can only come after it.',
  lesson: 'wr-05',
},
{
  id: 'md-21', domain: 'model', topic: 'Sort by column', type: 'order',
  stem: 'Month names sort alphabetically in every visual. Put the steps that make them sort in calendar order in order.',
  options: [
    'Make sure the calendar table has a Month Number column',
    'Select the Month Name column',
    'Column tools > Sort by column > Month Number',
    'Change Month Name to a Date data type',
  ],
  answer: [0, 1, 2],
  why: '**Sort by column** needs a column to sort by, so Month Number has to exist first. Then select the column you want sorted and choose what to sort it by. Month names aren\'t dates, so changing the type would fail.',
},
{
  id: 'md-22', domain: 'model', topic: 'Role-playing dimension', type: 'order',
  stem: 'Sales should also be shown by ship date, using the existing calendar table, which is already related to orders on order date. Put the steps in order.',
  options: [
    'Create a relationship from calendar[date] to orders[ship_date]; it is created inactive',
    'Create a measure: CALCULATE([Sales], USERELATIONSHIP(orders[ship_date], calendar[date]))',
    'Use the new measure in a visual with calendar dates on the axis',
    'Make the order date relationship inactive',
  ],
  answer: [0, 1, 2],
  why: 'A second relationship between the same two tables is **inactive**, and **USERELATIONSHIP** can only switch on a relationship that exists. The order date relationship stays active for every other measure.',
},
{
  id: 'vz-19', domain: 'visualize', topic: 'Bookmarks', type: 'order',
  stem: 'Two buttons should switch a page between a chart and a table. Put the steps in order.',
  options: [
    'Place the chart and the table on the page, in the same spot',
    'Hide the table in the Selection pane, then add a bookmark named Chart view',
    'Show the table and hide the chart, then add a bookmark named Table view',
    'Add two buttons, and set each one\'s action to one of the bookmarks',
  ],
  answer: [0, 1, 2, 3],
  why: 'A **bookmark** captures what is shown and hidden at the moment you add it, so each view has to be set up just before its bookmark. The **buttons** come last, because they point at bookmarks that must already exist.',
},
{
  id: 'dp-19', domain: 'deploy', topic: 'Row-level security', type: 'order',
  stem: 'Each city manager should see only their own city. Four of these actions set it up. Put them in order.',
  options: [
    'In Power BI Desktop, create a role with a DAX filter on the city',
    'Test the role with View as',
    'Publish the report',
    'In the service, add the managers as members of the role, in the semantic model\'s security settings',
    'Give the managers the Member role in the workspace',
  ],
  answer: [0, 1, 2, 3],
  why: 'Roles and their filters are defined in **Desktop**, tested there with **View as**, and published with the model. People are assigned to roles in the **service**. Making managers workspace Members would let them see everything, because RLS doesn\'t restrict people who can edit.',
},
{
  id: 'dp-20', domain: 'deploy', topic: 'Incremental refresh', type: 'order',
  stem: 'The orders table is too big to refresh in full every night. Four of these actions set up incremental refresh. Put them in order.',
  options: [
    'Create the RangeStart and RangeEnd parameters, of type Date/Time',
    'Filter the order date column with the two parameters',
    'Define the incremental refresh policy on the table',
    'Publish, and run the first refresh in the service',
    'Switch the table to DirectQuery',
  ],
  answer: [0, 1, 2, 3],
  why: 'The **parameters** have to exist before the filter can use them, and the **policy** can only be set on a table filtered by them. The first refresh in the service builds the partitions; later refreshes only reload the recent ones.',
},
{
  id: 'dp-21', domain: 'deploy', topic: 'Gateways', type: 'order',
  stem: 'A published report reads from a SQL Server in the office and needs to refresh every morning. Put the steps in order.',
  options: [
    'Install the on-premises data gateway on a machine that can reach the server',
    'Add a connection to the SQL Server on that gateway',
    "In the semantic model's settings, map its data source to that gateway connection",
    'Set the scheduled refresh times',
  ],
  answer: [0, 1, 2, 3],
  why: 'Each step needs the one before it. The **gateway** carries the connection; the **connection** holds the server and its credentials; the semantic model is **mapped** to the connection; and only a model that can reach its source can be **scheduled**.',
},

/* ── Case study: Kettle & Grind ────────────────────────── */
{
  id: 'kg-01', case: 'kettle', domain: 'deploy', topic: 'Gateways', type: 'single',
  stem: 'Which data source needs an on-premises data gateway for scheduled refresh?',
  options: [
    'The cafe sales in SQL Server in the Lagos office',
    'The online orders in Azure SQL Database',
    'The targets workbook in SharePoint Online',
    'All three of them',
  ],
  answer: [0],
  why: 'Only the **SQL Server in the office** is out of the service\'s reach. Azure SQL Database and SharePoint Online are cloud sources the service connects to directly.',
},
{
  id: 'kg-02', case: 'kettle', domain: 'prepare', topic: 'Storage modes', type: 'single',
  stem: 'Which storage mode should the online orders table use to meet its requirement?',
  options: ['DirectQuery', 'Import', 'Dual', 'A live connection'],
  answer: [0],
  why: 'Online sales must show orders placed minutes ago, so the table has to be queried at view time: **DirectQuery**. The cafe sales can stay on Import, which makes the model a composite model.',
},
{
  id: 'kg-03', case: 'kettle', domain: 'prepare', topic: 'Unpivot', type: 'single',
  stem: 'How should you shape the targets workbook in Power Query?',
  options: [
    'Select the City column, then Unpivot Other Columns',
    'Select the month columns, then Unpivot Columns',
    'Transpose the table, then promote the headers',
    'Pivot the City column',
  ],
  answer: [0],
  why: 'A new month column is added every month. **Unpivot Other Columns** keeps City and unpivots whatever else is there, so next month\'s column is included without editing the query.',
  lesson: 'wr-05',
},
{
  id: 'kg-04', case: 'kettle', domain: 'model', topic: 'Different grains', type: 'single',
  stem: 'Targets are monthly and per city; sales are per order line and per day. How should targets join the model, so they can be compared with sales by month and city?',
  options: [
    "Add a column holding the first day of each target's month, relate it to the calendar table, and relate targets to cities on the city",
    'Relate targets directly to the sales table on the city',
    'Merge the targets into the sales table in Power Query',
    'Relate targets to the sales table on the month number, in both directions',
  ],
  answer: [0],
  why: 'Targets are a second fact table at a coarser grain. Relating them to the **shared dimensions** (calendar and cities) lets one matrix by month and city show both. Pointing them at the date of the first of the month ties each target to its month. Relating one fact table straight to another creates many-to-many trouble.',
},
{
  id: 'kg-05', case: 'kettle', domain: 'deploy', topic: 'Distribution', type: 'multi',
  stem: 'What is needed to meet the finance requirement? Choose two.',
  options: [
    'Publish an app from the workspace, with finance as its audience',
    'Each person in finance has a Power BI Pro licence',
    'Add finance to the workspace with the Viewer role',
    'Use Publish to web',
  ],
  answer: [0, 1],
  why: 'An **app** shares the reports without giving access to the workspace, which the requirement rules out. The workspace is on shared capacity, so each viewer also needs a **Pro** licence. Publish to web would make the figures public.',
},

/* ── Case study: the online store ──────────────────────── */
{
  id: 'os-01', case: 'store', domain: 'model', topic: 'Role-playing dimension', type: 'single',
  stem: 'How should you meet the ship date requirement?',
  options: [
    'Add a second date table, a copy of calendar, related to orders[ship_date]',
    'Create an inactive relationship to ship_date and use USERELATIONSHIP in each measure',
    'Set the calendar relationship to filter in both directions',
    'Add a Ship Month column to the orders table',
  ],
  answer: [0],
  why: 'Users need a **slicer** of their own for ship dates, working alongside the order date slicer. USERELATIONSHIP switches relationships inside one measure, but a slicer on calendar would still filter by order date. A second, **role-playing** date table gives ship dates their own active relationship.',
},
{
  id: 'os-02', case: 'store', domain: 'deploy', topic: 'Incremental refresh', type: 'single',
  stem: 'How should you cut the nightly refresh time?',
  options: [
    'Configure incremental refresh on the orders table',
    'Switch every table to DirectQuery',
    'Schedule the refresh twice as often',
    'Remove the calendar table',
  ],
  answer: [0],
  why: 'Only the last few days of orders change. **Incremental refresh** reloads those partitions and keeps the older ones as they are.',
},
{
  id: 'os-03', case: 'store', domain: 'visualize', topic: 'Accessibility', type: 'single',
  stem: 'How should you fix the target status on the Overview page?',
  options: [
    'Add conditional formatting icons, so status is shown by shape as well as colour',
    'Switch to a colour-blind friendly red and green',
    'Remove the status column',
    'Add a legend explaining the colours',
  ],
  answer: [0],
  why: 'The requirement is that status can\'t depend on **colour alone**. Icons add a second cue, their shape, so nobody has to tell red from green. Different colours, or a legend for them, still rely on seeing colour.',
},
{
  id: 'os-04', case: 'store', domain: 'deploy', topic: 'Deployment pipelines', type: 'single',
  stem: 'What should you use to meet the testing requirement?',
  options: [
    'A deployment pipeline with development, test and production stages',
    'A second report file saved on a shared drive',
    'Publish to web for testers',
    'An app for the analysts',
  ],
  answer: [0],
  why: '**Deployment pipelines** move content from a development workspace to test, where it can be checked, and only then to production. The analysts have Premium Per User licences, which pipelines need.',
},
{
  id: 'os-05', case: 'store', domain: 'deploy', topic: 'Deployment pipelines', type: 'order',
  stem: 'Put the steps that set up the deployment pipeline and release the first change in order.',
  options: [
    'Create a deployment pipeline in the service',
    'Assign the analysts\' workspace to the Development stage',
    'Deploy from Development to Test, and check the report there',
    'Deploy from Test to Production',
    'Publish from Power BI Desktop straight to the production workspace',
  ],
  answer: [0, 1, 2, 3],
  why: 'The pipeline has to exist before a workspace can be **assigned** to a stage. Content then moves one stage at a time, and is checked in **Test** before it reaches Production. Publishing straight to production is exactly what the requirement is meant to stop.',
},
];

/* Case studies: a scenario, then questions that only make sense with it, as
   in the real exam. Questions refer back to the requirements by name. */
export const CASES = [
  {
    id: 'kettle',
    title: 'Kettle & Grind',
    overview: 'Kettle & Grind runs cafes in Lagos, Nairobi and Accra, and sells coffee beans and brewing kit online. Head office is in Lagos. The company is building its first Power BI reports.',
    sections: [
      {
        head: 'Existing environment',
        lines: [
          'Cafe sales are stored in a SQL Server database in the Lagos office.',
          'Online orders are stored in Azure SQL Database.',
          'Monthly sales targets are kept in an Excel workbook in SharePoint Online: one row per city, one column per month. A new month column is added every month.',
          'Report authors use Power BI Desktop. Everyone has a Power BI Pro licence, and the workspace is on shared capacity.',
        ],
      },
      {
        head: 'Requirements',
        lines: [
          'Cafe sales: the report must be refreshed every morning before 8am.',
          'Online sales: the report must show orders placed in the last few minutes.',
          'Targets: monthly targets must be compared with actual sales, by month and city.',
          'Finance: 40 people in finance must be able to use the reports, but must not have access to the workspace.',
        ],
      },
    ],
    questions: ['kg-01', 'kg-02', 'kg-03', 'kg-04', 'kg-05'],
  },
  {
    id: 'store',
    title: 'The online store',
    overview: 'The online store team has a Power BI report on orders, built by three analysts and used by about 60 people across the business.',
    sections: [
      {
        head: 'Existing environment',
        lines: [
          'The orders table holds 60 million rows, with an order_date and a ship_date column. Only orders from the last few days ever change.',
          'The model has one calendar table, related to orders on order_date.',
          'The full refresh takes two hours each night.',
          'The analysts publish from Power BI Desktop straight into the workspace the business uses. Twice this year a mistake reached users before anyone noticed.',
          'The analysts have Premium Per User licences.',
          'On the Overview page, a table shows each category\'s status against target in red or green text.',
        ],
      },
      {
        head: 'Requirements',
        lines: [
          'Ship date: users must be able to filter by ship month with its own slicer, alongside the order date slicer.',
          'Refresh: the nightly refresh must take much less time.',
          'Testing: every change must be checked before the business sees it.',
          'Accessibility: target status must not be shown by colour alone.',
        ],
      },
    ],
    questions: ['os-01', 'os-02', 'os-03', 'os-04', 'os-05'],
  },
];
