/* DAX practice problems, d01 to d20. A problem gives:
     measure    the name the learner must define
     reference  the right expression; helpers are its own supporting measures
     layouts    where it is tested: [] is the total, ['products[category]']
                a matrix by category, two columns a crossed matrix. Run tries
                only the first, so make that the telling one.
   Every cell and total must match. alt answers must pass, wrong ones fail. */

const SALES = 'SUMX(order_items, order_items[qty] * RELATED(products[price]))';
const REV = { Rev: SALES };
const CAT = 'products[category]';
const CITY = 'customers[city]';
const MONTH = 'calendar[month]';
const NAME = 'products[name]';

export const MORE_DAX = [

/* ── Easy ──────────────────────────────────────────────── */
{
  id: 'd01', difficulty: 'easy', lang: 'dax', tags: ['SUM', 'measures'],
  title: 'Units sold',
  prompt: [
    'Write a measure `Units`: how many items were sold — the total of `order_items[qty]`.',
    'It is tested overall, and in matrices by product category, customer city and month.',
  ],
  stub: 'Units = \n',
  measure: 'Units', reference: 'SUM(order_items[qty])',
  layouts: [[CAT], [], [CITY], [MONTH]],
  hint: 'One column, added up: `SUM(order_items[qty])`.',
  solution: 'Units = SUM(order_items[qty])\n',
  alt: ['Units = SUMX(order_items, order_items[qty])\n'],
  wrong: ['Units = COUNTROWS(order_items)\n'],
},
{
  id: 'd02', difficulty: 'easy', lang: 'dax', tags: ['SUMX', 'RELATED'],
  title: 'Revenue',
  prompt: [
    'Write `Rev`: the money taken — each order line\'s quantity times its product\'s price, all added up.',
    'The quantity is in `order_items`; the price is in `products`.',
  ],
  stub: 'Rev = \n',
  measure: 'Rev', reference: SALES,
  layouts: [[CAT], [], [CITY], [MONTH]],
  hint: `Row by row over order_items: \`${SALES}\`.`,
  solution: `Rev = ${SALES}\n`,
  alt: ['Rev = SUMX(order_items, RELATED(products[price]) * order_items[qty])\n'],
  wrong: ['Rev = SUM(products[price])\n', 'Rev = SUMX(order_items, RELATED(products[price]))\n'],
},
{
  id: 'd03', difficulty: 'easy', lang: 'dax', tags: ['DIVIDE', 'weighted average'],
  title: 'Average selling price',
  prompt: [
    'Write `Avg Price`: the average price of the items sold — revenue divided by units, so a mug bought ten times counts ten times.',
    'A plain average of the price list is not the answer.',
  ],
  stub: `Rev = ${SALES}\nUnits = SUM(order_items[qty])\nAvg Price = \n`,
  measure: 'Avg Price', reference: 'DIVIDE([Rev], [Units])',
  helpers: { Rev: SALES, Units: 'SUM(order_items[qty])' },
  layouts: [[CAT], [], [CITY], [MONTH]],
  hint: 'A weighted average divides the totals: `DIVIDE([Rev], [Units])`.',
  solution: `Rev = ${SALES}\nUnits = SUM(order_items[qty])\nAvg Price = DIVIDE([Rev], [Units])\n`,
  alt: [`Avg Price = DIVIDE(${SALES}, SUM(order_items[qty]))\n`],
  wrong: ['Avg Price = AVERAGE(products[price])\n', 'Avg Price = AVERAGEX(order_items, RELATED(products[price]))\n'],
},
{
  id: 'd04', difficulty: 'easy', lang: 'dax', tags: ['DISTINCTCOUNT'],
  title: 'How many bought?',
  prompt: [
    'Write `Buyers`: how many **different** customers placed an order.',
    'Tested overall, by month and by customer city.',
  ],
  stub: 'Buyers = \n',
  measure: 'Buyers', reference: 'DISTINCTCOUNT(orders[customer_id])',
  layouts: [[MONTH], [], [CITY]],
  hint: '`DISTINCTCOUNT(orders[customer_id])` counts each customer once, however many orders they placed.',
  solution: 'Buyers = DISTINCTCOUNT(orders[customer_id])\n',
  alt: ['Buyers = COUNTROWS(VALUES(orders[customer_id]))\n'],
  wrong: ['Buyers = COUNTROWS(orders)\n', 'Buyers = COUNTROWS(customers)\n'],
},
{
  id: 'd05', difficulty: 'easy', lang: 'dax', tags: ['CALCULATE', 'filters'],
  title: 'Cancelled orders',
  prompt: [
    'Write `Cancelled`: how many orders were cancelled.',
    'An order\'s `status` is `delivered`, `shipped` or `cancelled`.',
  ],
  stub: 'Cancelled = \n',
  measure: 'Cancelled', reference: 'CALCULATE(COUNTROWS(orders), orders[status] = "cancelled")',
  layouts: [[MONTH], [], [CITY]],
  hint: 'Count the orders, with a filter added: `CALCULATE(COUNTROWS(orders), orders[status] = "cancelled")`.',
  solution: 'Cancelled = CALCULATE(COUNTROWS(orders), orders[status] = "cancelled")\n',
  alt: ['Cancelled = COUNTROWS(FILTER(orders, orders[status] = "cancelled"))\n'],
  wrong: ['Cancelled = COUNTROWS(orders)\n', 'Cancelled = CALCULATE(COUNTROWS(orders), orders[status] <> "delivered")\n'],
},
{
  id: 'd06', difficulty: 'easy', lang: 'dax', tags: ['CALCULATE', 'replacing filters'],
  title: 'Beans, on every row',
  prompt: [
    'Write `Beans Rev`: revenue from the `beans` category.',
    'In a matrix by category it must show the beans figure on **every** row — a CALCULATE filter replaces the matrix\'s own.',
  ],
  stub: `Rev = ${SALES}\nBeans Rev = \n`,
  measure: 'Beans Rev', reference: 'CALCULATE([Rev], products[category] = "beans")', helpers: REV,
  layouts: [[CAT], [], [CITY]],
  hint: '`CALCULATE([Rev], products[category] = "beans")` — no KEEPFILTERS here.',
  solution: `Rev = ${SALES}\nBeans Rev = CALCULATE([Rev], products[category] = "beans")\n`,
  alt: [`Rev = ${SALES}\nBeans Rev = CALCULATE([Rev], products[category] IN {"beans"})\n`],
  wrong: [
    `Rev = ${SALES}\nBeans Rev = CALCULATE([Rev], KEEPFILTERS(products[category] = "beans"))\n`,
    'Beans Rev = SUMX(FILTER(order_items, RELATED(products[category]) = "beans"), order_items[qty] * RELATED(products[price]))\n',
  ],
},
{
  id: 'd07', difficulty: 'easy', lang: 'dax', tags: ['DIVIDE', 'grain'],
  title: 'Revenue per order',
  prompt: [
    'Write `Per Order`: the average revenue of an **order** — not of a single order line.',
    'An order can have several lines.',
  ],
  stub: `Rev = ${SALES}\nPer Order = \n`,
  measure: 'Per Order', reference: 'DIVIDE([Rev], COUNTROWS(orders))', helpers: REV,
  layouts: [[CITY], [], [MONTH]],
  hint: 'All the revenue, divided by the number of orders: `DIVIDE([Rev], COUNTROWS(orders))`.',
  solution: `Rev = ${SALES}\nPer Order = DIVIDE([Rev], COUNTROWS(orders))\n`,
  alt: [`Rev = ${SALES}\nPer Order = AVERAGEX(orders, [Rev])\n`],
  wrong: ['Per Order = AVERAGEX(order_items, order_items[qty] * RELATED(products[price]))\n'],
},

/* ── Medium ────────────────────────────────────────────── */
{
  id: 'd08', difficulty: 'medium', lang: 'dax', tags: ['ALL', 'shares'],
  title: 'Share within the view',
  prompt: [
    'Write `Share`: each product category\'s share of revenue, as a fraction.',
    'Inside a city it should be the category\'s share of **that city\'s** revenue — only the product filter gets removed.',
  ],
  stub: `Rev = ${SALES}\nShare = \n`,
  measure: 'Share', reference: 'DIVIDE([Rev], CALCULATE([Rev], ALL(products)))', helpers: REV,
  layouts: [[CITY, CAT], [CAT], []],
  hint: 'Divide by the same revenue with the product filters taken off: `CALCULATE([Rev], ALL(products))`.',
  solution: `Rev = ${SALES}\nShare = DIVIDE([Rev], CALCULATE([Rev], ALL(products)))\n`,
  alt: [
    `Rev = ${SALES}\nShare = DIVIDE([Rev], CALCULATE([Rev], REMOVEFILTERS(products)))\n`,
    `Rev = ${SALES}\nShare = DIVIDE([Rev], CALCULATE([Rev], ALL(products[category])))\n`,
  ],
  wrong: [
    `Rev = ${SALES}\nShare = DIVIDE([Rev], CALCULATE([Rev], ALL(order_items)))\n`,
    `Rev = ${SALES}\nShare = DIVIDE([Rev], CALCULATE([Rev], ALL(products[name])))\n`,
  ],
},
{
  id: 'd09', difficulty: 'medium', lang: 'dax', tags: ['CALCULATE', 'filters'],
  title: 'Delivered only',
  prompt: [
    'Write `Delivered Rev`: revenue from orders that were **delivered** — not cancelled, and not still on their way (shipped).',
  ],
  stub: `Rev = ${SALES}\nDelivered Rev = \n`,
  measure: 'Delivered Rev', reference: 'CALCULATE([Rev], orders[status] = "delivered")', helpers: REV,
  layouts: [[MONTH], [], [CAT]],
  hint: 'Say which status you want, rather than which you don\'t: `orders[status] = "delivered"`.',
  solution: `Rev = ${SALES}\nDelivered Rev = CALCULATE([Rev], orders[status] = "delivered")\n`,
  alt: [`Rev = ${SALES}\nDelivered Rev = CALCULATE([Rev], FILTER(orders, orders[status] = "delivered"))\n`],
  wrong: [`Rev = ${SALES}\nDelivered Rev = CALCULATE([Rev], orders[status] <> "cancelled")\n`],
},
{
  id: 'd10', difficulty: 'medium', lang: 'dax', tags: ['RANKX', 'context transition'],
  title: 'Rank the products',
  prompt: [
    'Write `Product Rank`: each product\'s place by revenue, 1 for the best seller. Ties share a place.',
    'It is also tested inside each city, where the ranking is that city\'s.',
  ],
  stub: `Rev = ${SALES}\nProduct Rank = \n`,
  measure: 'Product Rank', reference: 'RANKX(ALL(products[name]), [Rev])', helpers: REV,
  layouts: [[NAME], [CITY, NAME]],
  hint: 'Rank against every product — `ALL(products[name])` — by a **measure**, so each product\'s revenue is worked out for that product: `RANKX(ALL(products[name]), [Rev])`.',
  solution: `Rev = ${SALES}\nProduct Rank = RANKX(ALL(products[name]), [Rev])\n`,
  alt: [`Rev = ${SALES}\nProduct Rank = RANKX(ALL(products), [Rev])\n`],
  wrong: [
    `Product Rank = RANKX(ALL(products[name]), ${SALES})\n`,
    `Rev = ${SALES}\nProduct Rank = RANKX(products, [Rev])\n`,
  ],
},
{
  id: 'd11', difficulty: 'easy', lang: 'dax', tags: ['AVERAGE', 'BLANK'],
  title: 'Average rating',
  prompt: [
    'Write `Avg Rating`: the average of `cafe[rating]`.',
    'Some days have no rating. Those should be left out, not counted as zero.',
  ],
  stub: 'Avg Rating = \n',
  measure: 'Avg Rating', reference: 'AVERAGE(cafe[rating])',
  layouts: [['cafe[drink]'], [], ['cafe[city]'], [MONTH]],
  hint: '`AVERAGE` already skips blanks. Dividing by `COUNTROWS(cafe)` would count them.',
  solution: 'Avg Rating = AVERAGE(cafe[rating])\n',
  alt: ['Avg Rating = DIVIDE(SUM(cafe[rating]), COUNT(cafe[rating]))\n', 'Avg Rating = AVERAGEX(cafe, cafe[rating])\n'],
  wrong: ['Avg Rating = DIVIDE(SUM(cafe[rating]), COUNTROWS(cafe))\n'],
},
{
  id: 'd12', difficulty: 'easy', lang: 'dax', tags: ['CALCULATE', 'lookup tables'],
  title: 'Espresso by country',
  prompt: [
    'Write `Espresso Cups`: how many cups of `espresso` the cafe sold.',
    'It is tested in a matrix by `cities[country]`. That filter reaches `cafe` through the relationship on city.',
  ],
  stub: 'Espresso Cups = \n',
  measure: 'Espresso Cups', reference: 'CALCULATE(SUM(cafe[cups]), cafe[drink] = "espresso")',
  layouts: [['cities[country]'], [], [MONTH]],
  hint: '`CALCULATE(SUM(cafe[cups]), cafe[drink] = "espresso")`',
  solution: 'Espresso Cups = CALCULATE(SUM(cafe[cups]), cafe[drink] = "espresso")\n',
  alt: ['Espresso Cups = SUMX(FILTER(cafe, cafe[drink] = "espresso"), cafe[cups])\n'],
  wrong: ['Espresso Cups = SUM(cafe[cups])\n', 'Espresso Cups = CALCULATE(COUNTROWS(cafe), cafe[drink] = "espresso")\n'],
},
{
  id: 'd13', difficulty: 'medium', lang: 'dax', tags: ['FILTER', 'context transition'],
  title: 'Big orders',
  prompt: [
    'Write `Big Orders`: how many orders came to **100 or more** in revenue.',
    'An order\'s revenue is the sum of its lines, so each order has to be looked at on its own.',
  ],
  stub: `Rev = ${SALES}\nBig Orders = \n`,
  measure: 'Big Orders', reference: 'COUNTROWS(FILTER(orders, [Rev] >= 100))', helpers: REV,
  layouts: [[MONTH], [], [CITY]],
  hint: 'Go through `orders` and keep the ones where `[Rev] >= 100`. A measure inside FILTER is worked out for that one order: `COUNTROWS(FILTER(orders, [Rev] >= 100))`.',
  solution: `Rev = ${SALES}\nBig Orders = COUNTROWS(FILTER(orders, [Rev] >= 100))\n`,
  alt: [`Rev = ${SALES}\nBig Orders = SUMX(orders, IF([Rev] >= 100, 1))\n`],
  wrong: [`Big Orders = COUNTROWS(FILTER(orders, ${SALES} >= 100))\n`],
},
{
  id: 'd14', difficulty: 'medium', lang: 'dax', tags: ['FILTER', 'context transition'],
  title: 'Regulars',
  prompt: [
    'Write `Regulars`: how many customers placed **two or more** orders in the period being looked at.',
    'In a month, count only that month\'s orders.',
  ],
  stub: 'Regulars = \n',
  measure: 'Regulars', reference: 'COUNTROWS(FILTER(customers, CALCULATE(COUNTROWS(orders)) >= 2))',
  layouts: [[MONTH], [], [CITY]],
  hint: 'Go through the customers. Wrap the count in CALCULATE, so it counts each customer\'s own orders: `CALCULATE(COUNTROWS(orders)) >= 2`.',
  solution: 'Regulars = COUNTROWS(FILTER(customers, CALCULATE(COUNTROWS(orders)) >= 2))\n',
  alt: ['Regulars = COUNTROWS(FILTER(customers, COUNTROWS(RELATEDTABLE(orders)) >= 2))\n'],
  wrong: ['Regulars = COUNTROWS(FILTER(customers, COUNTROWS(orders) >= 2))\n'],
},
{
  id: 'd15', difficulty: 'medium', lang: 'dax', tags: ['time intelligence', 'TOTALYTD'],
  title: 'Year to date',
  prompt: [
    'Write `Rev YTD`: revenue from the start of the year up to the end of each month.',
  ],
  stub: `Rev = ${SALES}\nRev YTD = \n`,
  measure: 'Rev YTD', reference: 'TOTALYTD([Rev], calendar[date])', helpers: REV,
  layouts: [[MONTH], [CAT, MONTH], []],
  hint: '`TOTALYTD([Rev], calendar[date])`',
  solution: `Rev = ${SALES}\nRev YTD = TOTALYTD([Rev], calendar[date])\n`,
  alt: [`Rev = ${SALES}\nRev YTD = CALCULATE([Rev], DATESYTD(calendar[date]))\n`],
  wrong: [`Rev = ${SALES}\nRev YTD = CALCULATE([Rev], ALL(calendar))\n`],
},
{
  id: 'd16', difficulty: 'medium', lang: 'dax', tags: ['time intelligence', 'PREVIOUSMONTH'],
  title: 'Last month',
  prompt: [
    'Write `Prev Rev`: the revenue of the month **before** the one being looked at.',
    'In the total row the period is the whole year, and the month before that is before the data starts, so the total is blank.',
  ],
  stub: `Rev = ${SALES}\nPrev Rev = \n`,
  measure: 'Prev Rev', reference: 'CALCULATE([Rev], PREVIOUSMONTH(calendar[date]))', helpers: REV,
  layouts: [[MONTH], [CAT, MONTH]],
  hint: '`CALCULATE([Rev], PREVIOUSMONTH(calendar[date]))`',
  solution: `Rev = ${SALES}\nPrev Rev = CALCULATE([Rev], PREVIOUSMONTH(calendar[date]))\n`,
  alt: [],
  wrong: [`Rev = ${SALES}\nPrev Rev = CALCULATE([Rev], DATEADD(calendar[date], -1, MONTH))\n`, `Rev = ${SALES}\nPrev Rev = [Rev]\n`],
},
{
  id: 'd17', difficulty: 'medium', lang: 'dax', tags: ['ALL', 'shares'],
  title: 'Share across cities',
  prompt: [
    'Write `City Share`: each customer city\'s share of revenue.',
    'Inside a product category it is the city\'s share of **that category**. Only the city filter goes.',
  ],
  stub: `Rev = ${SALES}\nCity Share = \n`,
  measure: 'City Share', reference: 'DIVIDE([Rev], CALCULATE([Rev], ALL(customers[city])))', helpers: REV,
  layouts: [[CAT, CITY], [CITY]],
  hint: '`DIVIDE([Rev], CALCULATE([Rev], ALL(customers[city])))`',
  solution: `Rev = ${SALES}\nCity Share = DIVIDE([Rev], CALCULATE([Rev], ALL(customers[city])))\n`,
  alt: [
    `Rev = ${SALES}\nCity Share = DIVIDE([Rev], CALCULATE([Rev], ALL(customers)))\n`,
    `Rev = ${SALES}\nCity Share = DIVIDE([Rev], CALCULATE([Rev], REMOVEFILTERS(customers[city])))\n`,
  ],
  wrong: [
    `Rev = ${SALES}\nCity Share = DIVIDE([Rev], CALCULATE([Rev], ALL(products)))\n`,
    `Rev = ${SALES}\nCity Share = DIVIDE([Rev], CALCULATE([Rev], ALL(order_items)))\n`,
  ],
},
{
  id: 'd18', difficulty: 'medium', lang: 'dax', tags: ['DIVIDE', 'CALCULATE'],
  title: 'Cancellation rate',
  prompt: [
    'Write `Cancel Rate`: the fraction of orders that were cancelled, out of the orders in view.',
  ],
  stub: 'Cancel Rate = \n',
  measure: 'Cancel Rate',
  reference: 'DIVIDE(CALCULATE(COUNTROWS(orders), orders[status] = "cancelled"), COUNTROWS(orders))',
  layouts: [[MONTH], [], [CITY]],
  hint: 'The cancelled count over the plain count: `DIVIDE(CALCULATE(COUNTROWS(orders), orders[status] = "cancelled"), COUNTROWS(orders))`.',
  solution: 'Cancel Rate = DIVIDE(CALCULATE(COUNTROWS(orders), orders[status] = "cancelled"), COUNTROWS(orders))\n',
  alt: ['Cancel Rate = AVERAGEX(orders, IF(orders[status] = "cancelled", 1, 0))\n'],
  wrong: ['Cancel Rate = DIVIDE(CALCULATE(COUNTROWS(orders), orders[status] = "cancelled"), CALCULATE(COUNTROWS(orders), ALL(orders)))\n'],
},

/* ── Hard ──────────────────────────────────────────────── */
{
  id: 'd19', difficulty: 'hard', lang: 'dax', tags: ['time intelligence', 'VAR'],
  title: 'Growth on last month',
  prompt: [
    'Write `Growth`: how much revenue grew on the month before, as a fraction. 0.1 means 10% up.',
    'When there is no previous month to compare with, it should be blank.',
  ],
  stub: `Rev = ${SALES}\nGrowth = \n`,
  measure: 'Growth',
  reference: 'VAR prev = CALCULATE([Rev], PREVIOUSMONTH(calendar[date])) RETURN DIVIDE([Rev] - prev, prev)',
  helpers: REV,
  layouts: [[MONTH], [CAT, MONTH]],
  hint: 'Keep last month in a VAR, then `DIVIDE([Rev] - prev, prev)`. DIVIDE gives BLANK when prev is blank.',
  solution: `Rev = ${SALES}\nPrev Rev = CALCULATE([Rev], PREVIOUSMONTH(calendar[date]))\nGrowth = DIVIDE([Rev] - [Prev Rev], [Prev Rev])\n`,
  alt: [`Rev = ${SALES}\nGrowth =\n    VAR prev = CALCULATE([Rev], PREVIOUSMONTH(calendar[date]))\n    RETURN DIVIDE([Rev] - prev, prev)\n`],
  wrong: [`Rev = ${SALES}\nGrowth = DIVIDE([Rev], CALCULATE([Rev], PREVIOUSMONTH(calendar[date])))\n`],
},
{
  id: 'd20', difficulty: 'hard', lang: 'dax', tags: ['MAXX', 'context transition'],
  title: 'Best month',
  prompt: [
    'Write `Best Month`: the highest revenue any single month reached.',
    'Within a category it is that category\'s best month.',
  ],
  stub: `Rev = ${SALES}\nBest Month = \n`,
  measure: 'Best Month', reference: 'MAXX(VALUES(calendar[month]), [Rev])', helpers: REV,
  layouts: [[CAT], [], [CITY]],
  hint: 'Go through the months and take the biggest `[Rev]`: `MAXX(VALUES(calendar[month]), [Rev])`.',
  solution: `Rev = ${SALES}\nBest Month = MAXX(VALUES(calendar[month]), [Rev])\n`,
  alt: [`Rev = ${SALES}\nBest Month = MAXX(SUMMARIZE(calendar, calendar[month]), [Rev])\n`],
  wrong: [`Best Month = MAXX(VALUES(calendar[month]), ${SALES})\n`],
},
{
  id: 'd21', difficulty: 'hard', lang: 'dax', tags: ['AVERAGEX', 'BLANK'],
  title: 'A typical month',
  prompt: [
    'Write `Avg Month`: average revenue per month, counting only months that had sales.',
    'The calendar runs all year, and the shop\'s orders don\'t.',
  ],
  stub: `Rev = ${SALES}\nAvg Month = \n`,
  measure: 'Avg Month', reference: 'AVERAGEX(VALUES(calendar[month]), [Rev])', helpers: REV,
  layouts: [[CAT], [], [CITY]],
  hint: '`AVERAGEX(VALUES(calendar[month]), [Rev])`. A month with no sales gives BLANK, and AVERAGEX leaves blanks out.',
  solution: `Rev = ${SALES}\nAvg Month = AVERAGEX(VALUES(calendar[month]), [Rev])\n`,
  alt: [`Rev = ${SALES}\nAvg Month = DIVIDE([Rev], COUNTROWS(FILTER(VALUES(calendar[month]), [Rev] > 0)))\n`],
  wrong: [`Rev = ${SALES}\nAvg Month = DIVIDE([Rev], DISTINCTCOUNT(calendar[month]))\n`],
},
{
  id: 'd22', difficulty: 'hard', lang: 'dax', tags: ['RANKX', 'ALLEXCEPT'],
  title: 'Rank within the category',
  prompt: [
    'Write `Cat Rank`: each product\'s place by revenue **among the products in its own category**.',
    'It is tested in a matrix by category, then product.',
  ],
  stub: `Rev = ${SALES}\nCat Rank = \n`,
  measure: 'Cat Rank', reference: 'RANKX(ALLEXCEPT(products, products[category]), [Rev])', helpers: REV,
  layouts: [[CAT, NAME], [NAME]],
  hint: 'Rank against every product, but keep the category filter: `ALLEXCEPT(products, products[category])`.',
  solution: `Rev = ${SALES}\nCat Rank = RANKX(ALLEXCEPT(products, products[category]), [Rev])\n`,
  alt: [],
  wrong: [`Rev = ${SALES}\nCat Rank = RANKX(ALL(products), [Rev])\n`],
},
{
  id: 'd23', difficulty: 'hard', lang: 'dax', tags: ['VAR', 'ALL', 'dates'],
  title: 'New customers',
  prompt: [
    'Write `New Customers`: how many customers placed their **first ever** order in the period being looked at.',
    'Someone who first ordered in January and ordered again in March is new in January only.',
  ],
  stub: 'New Customers = \n',
  measure: 'New Customers',
  reference: 'VAR start = MIN(calendar[date]) RETURN COUNTROWS(FILTER(VALUES(orders[customer_id]), CALCULATE(MIN(orders[order_date]), ALL(calendar)) >= start))',
  layouts: [[MONTH], [], [CITY, MONTH]],
  hint: 'Keep the period\'s first day in a VAR. Then go through this period\'s buyers, and keep those whose first order, with the dates cleared by `ALL(calendar)`, is on or after it.',
  solution: 'New Customers =\n    VAR start = MIN(calendar[date])\n    RETURN COUNTROWS(\n        FILTER(VALUES(orders[customer_id]),\n            CALCULATE(MIN(orders[order_date]), ALL(calendar)) >= start))\n',
  alt: [],
  wrong: ['New Customers = DISTINCTCOUNT(orders[customer_id])\n'],
},
{
  id: 'd24', difficulty: 'hard', lang: 'dax', tags: ['one-way filters', 'SUMMARIZE'],
  title: 'Who bought beans?',
  prompt: [
    'Write `Buyers`: how many different customers bought something in the product category being looked at.',
    'The catch: a filter on `products` reaches `order_items` but never `orders`, because relationships filter one way.',
  ],
  stub: 'Buyers = \n',
  measure: 'Buyers', reference: 'COUNTROWS(SUMMARIZE(order_items, orders[customer_id]))',
  layouts: [[CAT], [], [NAME]],
  hint: 'Start from `order_items`, which the category filter does reach, and group it by the customer on the order: `COUNTROWS(SUMMARIZE(order_items, orders[customer_id]))`.',
  solution: 'Buyers = COUNTROWS(SUMMARIZE(order_items, orders[customer_id]))\n',
  // CALCULATE(DISTINCTCOUNT(orders[customer_id]), order_items) is right in Power BI
  // too, but our engine doesn't expand table filters (see the README), so it isn't listed.
  alt: ['Buyers = COUNTROWS(DISTINCT(SELECTCOLUMNS(order_items, "c", RELATED(orders[customer_id]))))\n'],
  wrong: ['Buyers = DISTINCTCOUNT(orders[customer_id])\n'],
},
];
